version: '2'
services:
    webpack:
        build: './webpack'
        command: ['webpack', '--progress', '--colors']
        volumes:
            - './webpack/src:/app/src'
            - './webpack/webpack.config.js:/app/webpack.config.js'
            - './webpack/assets:/app/assets'
            - './webpack/plugins:/app/plugins'
            - './webpack/build:/app/build'
        ports:
            - '3000:3000'
