version: '2'
services:
    nginx:
        image: 'nginx:alpine'
        volumes:
            - './webpack/build:/usr/share/nginx/html'
        ports:
            - '80:80'
    webpack:
        build: './webpack'
        command: ['webpack', '--progress', '--colors', '--watch']
        volumes:
            - './webpack/src:/app/src'
            - './webpack/webpack.config.js:/app/webpack.config.js'
            - './webpack/assets:/app/assets'
            - './webpack/plugins:/app/plugins'
            - './webpack/build:/app/build'
