version: '2'
services:
    api:
        build: './api'
        env_file: './.env'
        command: ['gulp', 'serve']
        volumes:
            - '/app/node_modules'
            - './api:/app'
            - './webpack/build:/build'
        ports:
            - '3000:3000'
    webpack:
        build: './webpack'
        command: ['webpack', '--progress', '--colors']
        volumes:
            - './webpack/src:/app/src'
            - './webpack/webpack.config.js:/app/webpack.config.js'
            - './webpack/assets:/app/assets'
            - './webpack/plugins:/app/plugins'
            - './webpack/build:/app/build'
