version: '2'
services:
    cca:
        image: 'python:2.7'
        command: ['python', '-m', 'SimpleHTTPServer']
        working_dir: '/src'
        volumes:
            - './src:/src'
        ports:
            - '8100:8000'
