version: '2'
services:
    api:
        build: './api'
        command: ['node', './src/express.js']
        volumes:
            - './api:/app'
            - './webpack/build:/build'
        ports:
            - '3000:3000'
    webpack:
        build: './webpack'
        command: ['webpack', '--progress', '--colors', '--watch']
        volumes:
            - './webpack/src:/app/src'
            - './webpack/webpack.config.js:/app/webpack.config.js'
            - './webpack/assets:/app/assets'
            - './webpack/plugins:/app/plugins'
            - './webpack/build:/app/build'
