version: '2'
services:
    nginx:
        image: 'nginx'
        volumes:
            - './build:/var/www:ro'
            - './site.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8100:80'
    webpack:
        build: '.'
        command: ['webpack', '--progress', '--colors']
        volumes:
            - './src:/app/src'
            - './webpack.config.js:/app/webpack.config.js'
            - './assets:/app/assets'
            - './plugins:/app/plugins'
            - './build:/app/build'
