---
swagger: '2.0'
host: 'communitychoiceboston.org'
info:
    version: 1.0.0
    title: 'Community Choice Energy Boston API'
    description: 'Backend logic for Community Choice Energy Boston'
basePath: '/api/v1'
schemes:
    - 'https'
produces:
    - 'application/json'
consumes:
    - 'application/json'
paths:
    '/calendar':
        get:
            produces:
                - 'application/json'
            responses:
                200:
                    description: 'OK'
                400:
                    description: 'Bad Request'
                500:
                    description: 'Internal Error'
            'x-amazon-apigateway-integration':
                type: 'aws_proxy'
                uri: 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${lambda_arn}/invocations'
                httpMethod: 'POST'
                credentials: '${iam_invoke_arn}'
                passthroughBehavior: 'never'
    '/posts':
        get:
            produces:
                - 'application/json'
            responses:
                200:
                    description: 'OK'
                400:
                    description: 'Bad Request'
                500:
                    description: 'Internal Error'
            'x-amazon-apigateway-integration':
                type: 'aws_proxy'
                uri: 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${lambda_arn}/invocations'
                httpMethod: 'POST'
                credentials: '${iam_invoke_arn}'
                passthroughBehavior: 'never'
    '/petition':
        post:
            produces:
                - 'application/json'
            parameters:
                - name: 'payload'
                  in: 'body'
                  schema:
                    $ref: '#/definitions/PetitionPayload'
                  required: true
            responses:
                200:
                    description: 'OK'
                400:
                    description: 'Bad Request'
                500:
                    description: 'Internal Error'
            'x-amazon-apigateway-integration':
                type: 'aws_proxy'
                uri: 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${lambda_arn}/invocations'
                httpMethod: 'POST'
                credentials: '${iam_invoke_arn}'
                passthroughBehavior: 'never'

definitions:
  PetitionPayload:
    type: 'object'
    properties:
      name_first:
        type: 'string'
      name_last:
        type: 'string'
      email:
        type: 'string'
      zip:
        type: 'string'
      phone:
        type: 'string'
      address1:
        type: 'string'
      address2:
        type: 'string'
      city:
        type: 'string'
      contact-pref:
        type: 'string'
